config/routes.rb
PropertyManagement::Application.routes.draw do
  resources :buildings
  resources :owners
end

app/models/building.rb
class Building < ActiveRecord::Base
  belongs_to :owner

  validates :street_address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :postal_code, presence: true
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  has_many :buildings, dependent: :nullify

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  def new
    @building = Building.new
  end

  def create
    @building = Building.new(building_params)

    if @building.save
      redirect_to new_building_path
      flash[:notice] = "I LOVED THAT BUILDING, THANKS!"
    else
      render 'new'
    end
  end

  def show
    @building = Building.find(params[:id])
  end

  private

  def building_params
    params.require(:building).permit(:street_address, :city, :state, :postal_code, :description, :owner_id)
  end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  def new
    @owner = Owner.new
  end

  def create
    @owner = Owner.new(owner_params)

    if @owner.save
      redirect_to @owner
      flash[:notice] = "But, if you really think about it, can anyone really OWN a building?"
    else
      flash.now[:alert] = "There was an error with the info you provided"
      render 'new'
    end
  end

  def show
    @owner = Owner.find(params[:id])
  end

  private

  def owner_params
    params.require(:owner).permit(:first_name, :last_name, :email, :company)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/buildings/new.html.erb
<h1>I LOVE BUILDINGS! TELL ME ABOUT SOME BUILDING!</h1>

<%= simple_form_for @building do |f| %>
  <%= f.input :street_address %>
  <%= f.input :city %>
  <%= f.input :state %>
  <%= f.input :postal_code %>
  <%= f.input :description %>
  <%= f.association :owner, label_method: :email %>

  <%= f.button :submit, "USER FRIENDLY BUILDING ADDITION BUTTON" %>
<% end %>

app/views/buildings/show.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<table>
  <tr>
    <td><%= "Street Address: #{@building.street_address}" %></td>
  </tr><tr>
    <td><%= "City: #{@building.city}" %></td>
  </tr><tr>
    <td><%= "State: #{@building.state}" %></td>
  </tr><tr>
    <td><%= "Postal Code: #{@building.postal_code}" %></td>
  </tr><tr>
    <td><%= "Description: #{@building.description}" %></td>
  </tr><tr>
    <td><%= "Owner: #{@building.owner}" %></td>
</table>

 <li> <%= link_to 'ADD MORE', new_building_path %> </li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PropertyManagement</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |type, message|  %>
  <div class="<%= type %>"><%= message %></div>
<% end %>

<%= yield %>

</body>
</html>

app/views/owners/index.html.erb
<% @owners.each do |owner| %>
  <div>
    <p><%= owner.first_name %></p>
    <p><%= owner.last_name %></p>
    <p><%= owner.email %></p>
    <p><%= owner.company %></p>
    <%= link_to "NO ONE CAN OWN A BUILDING", owner, method: :delete %>
  </div>
<% end %>

app/views/owners/new.html.erb
<h1>Building ownersssssss</h1>

<%= simple_form_for @owner do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email %>
  <%= f.input :company %>
  <%= f.button :submit, "This person owns a BUILDING!! Whoa!" %>
  <% end %>

app/views/owners/show.html.erb
<table>
  <tr>
    <td><%= "First Name: #{@owner.first_name}" %></td>
  </tr><tr>
    <td><%= "City: #{@owner.last_name}" %></td>
  </tr><tr>
    <td><%= "State: #{@owner.email}" %></td>
  </tr><tr>
    <td><%= "Postal Code: #{@owner.company}" %></td>
  </tr>
</table>

 <li> <%= link_to 'ADD MORE', new_owner_path %> </li>